In [1]:
import numpy as np

## numpy array

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem) # numpy dizisi

array([20, 30, 40])

In [5]:
matrixListesi = [[10,20,30], [20,30,40], [30,40,50]]

In [6]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [7]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2) # 2 stepsize

array([0, 2, 4, 6, 8])

## zeros

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,2)) # tuple olan (2,2)'yi ver

array([[0., 0.],
       [0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

## linspace

In [14]:
np.linspace(0,20,4) # 20 dahil

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

## eye

In [15]:
np.eye(3) # diagonal 1,1,1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [16]:
np.random.randn(4) # tek boyutlu numpy dizisi

array([-0.81353859,  0.38861851,  0.42864897,  0.2327974 ])

In [17]:
np.random.randn(4,4) # iki boyutlu numpy dizisi

array([[-1.46796325, -1.0525173 ,  0.74298035,  1.47144665],
       [-2.11522521,  0.23790805,  0.7611874 , -0.87744469],
       [-0.41327166,  1.08144024, -0.14170744,  0.04595596],
       [-1.13596381,  2.15424086, -1.20409385, -0.87498195]])

In [18]:
np.random.randint(1,10,(3,3)) # 10 dahil değil

array([[5, 6, 8],
       [5, 4, 5],
       [4, 8, 9]])

In [19]:
benimNumpyDizim = np.arange(30)

In [23]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
benimRandomDizim = np.random.randint(0,100,30)

In [21]:
benimRandomDizim

array([76, 35, 70, 25, 61, 24, 55, 42, 39, 74, 92, 46, 81, 60, 78, 34, 50,
       53, 15, 30, 58, 40, 39, 22, 58, 77, 84,  3, 44, 54])

## numpy dizi methodları

In [22]:
benimNumpyDizim.reshape(5,6) # yeniden şekillendirme

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
benimNumpyDizim.max()

29

In [25]:
benimNumpyDizim.min()

0

In [26]:
benimRandomDizim.argmax() # max değerin hangi indexte olduğunu söyler

10

In [28]:
benimNumpyDizim.shape # şeklini bastırır

(30,)