In [4]:
import numpy as np

In [5]:
benimDizim = np.arange(0,15)

In [6]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
benimDizim[3:5]

array([3, 4])

In [8]:
benimDizim[3:8] = -5

In [9]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [10]:
baskaDizi = np.arange(0,24)

In [11]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
slicingDizisi = baskaDizi[4:9]

In [15]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [16]:
slicingDizisi[:] = 300

In [17]:
slicingDizisi

array([300, 300, 300, 300, 300])

In [19]:
baskaDizi # bir dizi oluşturup değişiklik yapmak ana diziyi de etkiler

array([  0,   1,   2,   3, 300, 300, 300, 300, 300,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [20]:
ornekDizi = np.arange(0,24)

In [21]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
ornekDiziKopyasi = ornekDizi.copy()

In [23]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [27]:
ornekDiziKopyaSlicing[:] = 800

In [29]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [32]:
ornekDiziKopyasi # copy olan değişti, orijinal aynı kaldı

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

## matrix

In [33]:
benimListem = [[10,20,30], [20,30,40], [30,40,50]]

In [34]:
benimListem

[[10, 20, 30], [20, 30, 40], [30, 40, 50]]

In [35]:
benimMatrixDizim = np.array(benimListem)

In [36]:
benimMatrixDizim 

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [37]:
benimMatrixDizim[1][2]

40

In [38]:
benimMatrixDizim[1,2]

40

In [39]:
benimMatrixDizim[1:,2] # 1. index den sonrasının 2. indexteki elemanı

array([40, 50])

In [41]:
yeniListe = [[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]]

In [42]:
yeniMatrix = np.array(yeniListe)

In [43]:
yeniMatrix

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [47]:
yeniMatrix[[1,2]] # indexleri liste gibi yaz array versin

numpy.ndarray

## operasyonlar

In [48]:
yeniBirDizi = np.random.randint(1,100,20)

In [49]:
yeniBirDizi

array([45, 24,  4, 93, 45, 43, 68, 61, 20, 19, 64, 93, 28, 58, 71, 58, 64,
       47, 64, 49])

In [50]:
yeniBirDizi > 24

array([ True, False, False,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [51]:
sonucDizisi = yeniBirDizi > 24

In [52]:
sonucDizisi

array([ True, False, False,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [54]:
yeniBirDizi[sonucDizisi] # sadece 24'ten büyükleri bastırır

array([45, 93, 45, 43, 68, 61, 64, 93, 28, 58, 71, 58, 64, 47, 64, 49])

In [55]:
sonDizi = np.arange(0,24)

In [56]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [57]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [60]:
np.max(sonDizi)

23

In [64]:
sonDizi.argmin()

0